apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderelection
  labels:
    app: leaderelection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leaderelection
  template:
    metadata:
      labels:
        app: leaderelection
    spec:
      serviceAccountName: leaderelection
      containers:
        - name: leader
          image: nickytd/leaderelection
          args:
            - -v=4
            - -id=$(POD_NAME)
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
