apiVersion: v1
kind: ServiceAccount
metadata:
  name: leaderelection
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leaderelection
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaderelection
subjects:
  - kind: ServiceAccount
    name: leaderelection
roleRef:
  kind: Role
  name: leaderelection
  apiGroup: rbac.authorization.k8s.io

